name: Deploy to Server

on:
  workflow_dispatch:  # This allows you to manually trigger the action
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Enable debugging
        run: set -x

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to server
        run: |
          rsync -avz -x -e "ssh -p22 -vvv -o StrictHostKeyChecking=no" ./wp-content/ cudend7@cp2.uk.netnerd.com:/home/cudend7/carehome.cuden.co.uk 2> ssh_debug.log || cat ssh_debug.log
